apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: node:23.3.0
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.port }}
          {{- if .Values.mountPath }}
          volumeMounts:
            - name: "{{ .Chart.Name }}-src"
              mountPath: /app/src/
          {{- end }}
      {{- if .Values.mountPath }}
      volumes:
        - name: "{{ .Chart.Name }}-src"
          hostPath:
            path: {{ .Values.mountPath }}
      {{- end }}
