FROM node:23.3.0 AS base

FROM base AS deps-installer
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm i

FROM base AS dev-runner
WORKDIR /usr/src/app
COPY --from=deps-installer /usr/src/app/node_modules ./node_modules
COPY . .
RUN npm run build
CMD ["npm", "run", "dev"]
