FROM node:23-alpine AS base
RUN apk add --update curl && \
  rm -rf /var/cache/apk/*

FROM base AS deps-installer
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package*.json ./
RUN npm i

# TODO
# 以下でいけるはずだが、マウントの挙動によって/app/src/配下のファイルが全て消失してしまうためエラーになる
# 恐らく消失ではなく読み取り専用になっているだけっぽい？
# FROM base AS runner
# WORKDIR /app
# COPY . .
# COPY --from=deps-installer /app/ ./
# EXPOSE 3000
# CMD ["npm", "run", "dev"]


FROM base AS builder
WORKDIR /app
COPY --from=deps-installer /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM base AS runner
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder . .
EXPOSE 3000
CMD ["npm", "run", "start"]
