apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: nextjs-diary

build:
  artifacts:
    - image: node
      context: ../../
      docker:
        dockerfile: ./app/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: false
deploy:
  helm:
    releases:
      - name: nextjs-diary
        chartPath: helm/deployment
        valuesFiles:
          - helm/values.yaml
profiles:
  - name: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: ./app/Dockerfile.dev
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/0
        value: helm/dev-values.yaml
