name: GitHub Actions Demo
on: [push]
defaults:
  run:
    working-directory: nextjs-diary
jobs:
  installNodeEnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: '23.0'
  dependenciesInstall:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run test:e2e
